config:
  WOLF:
    WOLF: 0
    BOA: 10
    FROG: 5
    FOX: 10
    BEAR: 0
    EAGLE: 10
    HORSE: 30
    DEER: 40
    RABBIT: 70
    MOUSE: 90
    GOAT: 60
    SHEEP: 70
    BOAR: 20
    BUFFALO: 30
    DUCK: 80
    CATERPILLAR: 0
  BOA:
    WOLF: 0
    BOA: 0
    FROG: 90
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 50
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 50
    CATERPILLAR: 90
  FOX:
    WOLF: 0
    BOA: 20
    FROG: 10
    FOX: 0
    BEAR: 0
    EAGLE: 10
    HORSE: 0
    DEER: 5
    RABBIT: 70
    MOUSE: 90
    GOAT: 20
    SHEEP: 20
    BOAR: 5
    BUFFALO: 0
    DUCK: 80
    CATERPILLAR: 0
  BEAR:
    WOLF: 20
    BOA: 30
    FROG: 5
    FOX: 20
    BEAR: 0
    EAGLE: 30
    HORSE: 70
    DEER: 80
    RABBIT: 80
    MOUSE: 90
    GOAT: 70
    SHEEP: 70
    BOAR: 60
    BUFFALO: 75
    DUCK: 80
    CATERPILLAR: 0
  EAGLE:
    WOLF: 0
    BOA: 50
    FROG: 90
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 90
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 85
    CATERPILLAR: 20
  HORSE:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  DEER:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  RABBIT:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  MOUSE:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  GOAT:
    WOLF: 0
    BOA: 0
    FROG: 1
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  SHEEP:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  BOAR:
    WOLF: 0
    BOA: 0
    FROG: 1
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  BUFFALO:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
  DUCK:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 50
  CATERPILLAR:
    WOLF: 0
    BOA: 0
    FROG: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
