config:
  WOLF:
    WOLF: 0
    ANACONDA: 10
    FOX: 10
    BEAR: 0
    EAGLE: 10
    HORSE: 30
    DEER: 40
    RABBIT: 70
    MOUSE: 90
    GOAT: 60
    SHEEP: 70
    BOAR: 20
    BUFFALO: 30
    DUCK: 80
    CATERPILLAR: 0
    PLANT: 0
  ANACONDA:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 50
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 50
    CATERPILLAR: 90
    PLANT: 0
  FOX:
    WOLF: 0
    ANACONDA: 20
    FOX: 0
    BEAR: 0
    EAGLE: 10
    HORSE: 0
    DEER: 5
    RABBIT: 70
    MOUSE: 90
    GOAT: 20
    SHEEP: 20
    BOAR: 5
    BUFFALO: 0
    DUCK: 80
    CATERPILLAR: 0
    PLANT: 0
  BEAR:
    WOLF: 20
    ANACONDA: 30
    FOX: 20
    BEAR: 0
    EAGLE: 30
    HORSE: 70
    DEER: 80
    RABBIT: 80
    MOUSE: 90
    GOAT: 70
    SHEEP: 70
    BOAR: 60
    BUFFALO: 75
    DUCK: 80
    CATERPILLAR: 0
    PLANT: 0
  EAGLE:
    WOLF: 0
    ANACONDA: 50
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 90
    MOUSE: 90
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 85
    CATERPILLAR: 20
    PLANT: 0
  HORSE:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  DEER:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  RABBIT:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  MOUSE:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  GOAT:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  SHEEP:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  BOAR:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  BUFFALO:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  DUCK:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 50
    PLANT: 100
  CATERPILLAR:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 100
  PLANT:
    WOLF: 0
    ANACONDA: 0
    FOX: 0
    BEAR: 0
    EAGLE: 0
    HORSE: 0
    DEER: 0
    RABBIT: 0
    MOUSE: 0
    GOAT: 0
    SHEEP: 0
    BOAR: 0
    BUFFALO: 0
    DUCK: 0
    CATERPILLAR: 0
    PLANT: 0